In [1]:
import numpy as np
matrixB = np.array([[-3, 9, 5],
                [-4, 0, 1],
                [6, 3, 0]])

print(f'Matrix B=\n{matrixB}')

matrixB_transpose = matrixB.transpose()

print(f'Transpose Matrix=\n{matrixB_transpose}')

Matrix B=
[[-3  9  5]
 [-4  0  1]
 [ 6  3  0]]
Transpose Matrix=
[[-3 -4  6]
 [ 9  0  3]
 [ 5  1  0]]
